import type { NextPage } from "next";
import Head from "next/head";

import { Layout } from "components";

const Home: NextPage = () => {
  return (
    <Layout>
      <Head>
        <title>보라 포트폴리오</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>홈 입니다</h1>
    </Layout>
  );
};

export default Home;
